# This script deploys your website automatically
name: CI

# Only trigger this script when you push to the master branch
on:
    push:
        branches: [main]

# Specify the tasks to run when this script gets triggered
jobs:
    build:
        runs-on: ubuntu-latest

        # Download our master branch
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: use Node 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
            - name: Install dependencies
              run: npm i
            - name: build
              run: npm run build
            - name: Archive build
              if: success()
              uses: actions/upload-artifact@v1
              with:
                  name: deploy_dist
                  path: dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Download build
              uses: actions/download-artifact@v1
              with:
                  name: deploy_dist
            - name: Deploy to GitHub pages
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: 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
                  BRANCH: gh-pages
                  FOLDER: deploy_dist/shenncrafts
